#version: '3.8'

volumes:
  fact-data:
networks:
    fact-network:
      name: fact-network

services:
  mysqldb:
    image: mysql:lts
#    command: --mysql-native-password=ON
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=fact
      - MYSQL_USER=fact
      - MYSQL_PASSWORD=ZDeHN2F75LhZDbuOlsCZgccsevQ0gJ6HtxGlH/3nVpI=
      - MYSQL_ROOT_PASSWORD=qTfVk5CGgVzI2ScXMia8wcGlli1JxzL0c1kXZ7TB3nM=
    networks:
        - fact-network
    volumes:
      - fact-data:/var/lib/mysql-fact
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      retries: 5
      interval: 5s
      timeout: 30s

  fact-api:
    build: .
    ports:
      - "9000:8080"
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
        - fact-network
    environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/fact
        - SPRING_DATASOURCE_USERNAME=fact
        - SPRING_DATASOURCE_PASSWORD=ZDeHN2F75LhZDbuOlsCZgccsevQ0gJ6HtxGlH/3nVpI=
        - MY_SECRETKEY=36415d5e4da14415bc338564d55e56f561bbd3e0c1bf5e0c7f6386266d3cc45b33eac81f900ba5dcdb164ccfb6361197d96a9ae699388762bd02dfbc29500968
        - SPRING_PROFILES_ACTIVE=prod